BOC/Controllers/FlightDateController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BOC.Models;
using System.Net.Http;
using Newtonsoft.Json.Linq;
using Nancy.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Globalization;

namespace BOC.Controllers
{
    public class FlightDateController : Controller
    {
        [HttpGet]
        public IActionResult Index(LoungeModel model)
        {
           
            //Create viewbag content Route
            IEnumerable<SelectListItem> Routing = new[]
            {

                new SelectListItem { Value = "ALL", Text = "ALL" },
                new SelectListItem { Value = "INT", Text = "INT" },
                new SelectListItem { Value = "DOM", Text = "DOM" },

            };

            ViewBag.List = Routing;
            //Get Session Token
            var token = HttpContext.Session.GetString("Token");
            //Access API with Header
            Url airportlst = new Url();
            string uri = airportlst.Get("AirportList");

           
            HttpClient Client = new HttpClient();

            Client.DefaultRequestHeaders.Add("Authorization", token);
            var req = new HttpRequestMessage(HttpMethod.Post, uri);

            string Content;
            HttpResponseMessage res;
            res = Client.SendAsync(req).Result;
            Content = res.Content.ReadAsStringAsync().Result;
            var oData = JObject.Parse(Content);

            //Bind Json To List 
            JavaScriptSerializer ser = new JavaScriptSerializer();
            List<AirportList> lst = ser.Deserialize<List<AirportList>>(oData["Data"].ToString());//str is JSON string.
            for (int i = 0; i < lst.Count; i++)
            {
                lst[i].ID = i + 1;
            }
            model.ListAirport = lst;
            return View(model);
        }
        [HttpPost]
        public IActionResult Detail(FlightModel model)
        {
                //Get Session TypeOfDevice
                var typeofdevices = HttpContext.Session.GetString("TypeOfDevice");
                if (model.TimeZone == null) { model.TimeZone = "HAN"; }
                //Set Session TimeZone
                HttpContext.Session.SetString("TimeZone", model.TimeZone.ToString());

                if (model.AirportChoose == null)
                {
                    model.AirportChoose = "";
                }

                //Set Session AirportChoose
                HttpContext.Session.SetString("AirportChoose", model.AirportChoose.ToString());

                if (model.Key == null)
                {
                    model.Key = "";
                }
                var KeySearch = model.Key.ToString();
                if (model.ViewType == null)
                {
                    model.ViewType = "";
                }
                var ViewType = model.ViewType.ToString();


                //Parse string date from dd/MM/yyyy to yyyy-MM-dd
                DateTime dt = DateTime.ParseExact(model.Date.ToString(), "dd/MM/yyyy", CultureInfo.InvariantCulture);

                var date = dt.ToString("yyyy-MM-dd");
                ViewData["FlightID"] = "0";
                ViewData["TimeZone"] = model.TimeZone.ToString();
                ViewData["Date"] = date;
                ViewData["KeySsearch"] = KeySearch.ToString();
                ViewData["Int_Dom"] = model.SelectedRouting.ToString();
                ViewData["ViewType"] = ViewType.ToString();
                ViewData["AutoHide"] = model.AutoHide.ToString();
                
            if (typeofdevices == "DeskTop")
            {
                return View();
            }
            else
            {

                return RedirectToAction("Index", "FlightDateMobile",  new { @TimeZone = model.TimeZone.ToString(), @Date = date, @Key= KeySearch.ToString() , @SelectedRouting = model.SelectedRouting.ToString() , @VType= ViewType.ToString() , @AutoHide = model.AutoHide.ToString() }) ;
        
            }
        }

        public IActionResult FlightOne(string FlightId)
        {
           
            //Get Session TimeZone
            var TimeZone = HttpContext.Session.GetString("TimeZone");
            //Get Session Token
            var token = HttpContext.Session.GetString("Token");
            #region ONE FLIGHT
            ////Access API to get One Flight 
            Url flightget = new Url();
            string uri = flightget.Get("FlightOneGet");

            HttpClient Client = new HttpClient();
            var nvc = new List<KeyValuePair<string, string>>();
            nvc.Add(new KeyValuePair<string, string>("FlightID", FlightId));
            nvc.Add(new KeyValuePair<string, string>("TimeZone", TimeZone));
            Client.DefaultRequestHeaders.Add("Authorization", token);
            var req = new HttpRequestMessage(HttpMethod.Post, uri) { Content = new FormUrlEncodedContent(nvc) };

            string Content;
            HttpResponseMessage res;
            res = Client.SendAsync(req).Result;
            Content = res.Content.ReadAsStringAsync().Result;

            JObject ser = JObject.Parse(Content);
            Int32 _Result = (int)ser.SelectToken("ResultCode");

            List<Items> lst = new List<Items>();
            var ser2 = ser.SelectToken("Data");
            List<JToken> data = new List<JToken>(ser2.Children());
            var model = new FlightOneModel();

            foreach (var item in data)
            {                

                var PaxEst_Full = item.SelectToken("PaxEst_Full");
                model.PaxEst_Full = JsonConvert.DeserializeObject<Items>(PaxEst_Full.ToString());

                var PaxEst_Total = item.SelectToken("PaxEst_Total");
                model.PaxEst_Total = JsonConvert.DeserializeObject<Items>(PaxEst_Total.ToString());

                var Pax_Full = item.SelectToken("Pax_Full");
                model.Pax_Full = JsonConvert.DeserializeObject<Items>(Pax_Full.ToString());

                var Pax_Total = item.SelectToken("Pax_Total");
                model.Pax_Total = JsonConvert.DeserializeObject<Items>(Pax_Total.ToString());

                var Crew= item.SelectToken("Crew");
                model.Crew = JsonConvert.DeserializeObject<Items>(Crew.ToString());

                var Cargo_Full = item.SelectToken("Cargo_Full");
                model.Cargo_Full = JsonConvert.DeserializeObject<Items>(Cargo_Full.ToString());

                var Mail = item.SelectToken("Mail");
                model.Mail = JsonConvert.DeserializeObject<Items>(Mail.ToString());

                var Co_Mat_Full = item.SelectToken("Co_Mat_Full");
                model.Co_Mat_Full = JsonConvert.DeserializeObject<Items>(Co_Mat_Full.ToString());

                var Fuel_Remmain = item.SelectToken("Fuel_Remmain");
                model.Fuel_Remmain = JsonConvert.DeserializeObject<Items>(Fuel_Remmain.ToString());

                var Fuel_Topup = item.SelectToken("Fuel_Topup");
                model.Fuel_Topup = JsonConvert.DeserializeObject<Items>(Fuel_Topup.ToString());

                var Fuel_Trip = item.SelectToken("Fuel_Trip");
                model.Fuel_Trip = JsonConvert.DeserializeObject<Items>(Fuel_Trip.ToString());

                string FlightID= item.SelectToken("FlightID").ToString();
                string TimeKey = item.SelectToken("TimeKey").ToString();

                var Date = item.SelectToken("Date");
                model.Date = JsonConvert.DeserializeObject<Items>(Date.ToString());
                var dd = model.Date.Value.ToString();
                string[] collection = dd.Split('-');
                // to get the full month name
                string monthName = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(Int16.Parse(collection[1]));
                string day = collection[2];
                TempData["Date"] = day + monthName;

                var FltNo = item.SelectToken("FltNo");
                model.FltNo = JsonConvert.DeserializeObject<Items>(FltNo.ToString());
                TempData["FlightNo"] = model.FltNo.Value.ToString();

                var RegisterNo = item.SelectToken("RegisterNo");
                model.RegisterNo = JsonConvert.DeserializeObject<Items>(RegisterNo.ToString());

                var Aircraft = item.SelectToken("Aircraft");
                model.Aircraft = JsonConvert.DeserializeObject<Items>(Aircraft.ToString());

                var Route = item.SelectToken("Route");
                model.Route = JsonConvert.DeserializeObject<Items>(Route.ToString());
                TempData["Routing"] = model.Route.Value.ToString();

                var DateTime_ATD = item.SelectToken("DateTime_ATD");
                model.DateTime_ATD = JsonConvert.DeserializeObject<Items>(DateTime_ATD.ToString());

                var DateTime_ATA = item.SelectToken("DateTime_ATA");
                model.DateTime_ATA = JsonConvert.DeserializeObject<Items>(DateTime_ATA.ToString());

                var STD = item.SelectToken("STD");
                model.STD = JsonConvert.DeserializeObject<Items>(STD.ToString());

                var ETD = item.SelectToken("ETD");
                model.ETD = JsonConvert.DeserializeObject<Items>(ETD.ToString());

                var BDT = item.SelectToken("BDT");
                model.BDT = JsonConvert.DeserializeObject<Items>(BDT.ToString());

                var DoorClose = item.SelectToken("DoorClose");
                model.DoorClose = JsonConvert.DeserializeObject<Items>(DoorClose.ToString());

                var TOff = item.SelectToken("TOff");
                model.TOff = JsonConvert.DeserializeObject<Items>(TOff.ToString());

                var STA = item.SelectToken("STA");
                model.STA = JsonConvert.DeserializeObject<Items>(STA.ToString());

                var ETA = item.SelectToken("ETA");

BOC/Views/FlightDate/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_DeskTop.cshtml";
}

<style>
    .dx-scrollable {
    width:auto!important;
}
</style>


<h1>FLIGHT DATE: @ViewData["Date"].ToString()</h1>

@(Html.DevExtreme().DataGrid<BOC.Models.Flight>()
.ID("Container")
.DataSource(
    ds => ds.Mvc()
        .Controller("FlightDateApi")
        .LoadAction("Get")
        .LoadParams(new { TimeZone = @ViewData["TimeZone"], date = @ViewData["Date"], key = @ViewData["KeySsearch"], SelectedRouting = @ViewData["Int_Dom"], ViewType = @ViewData["ViewType"], AutoHide = @ViewData["AutoHide"] })
)
.RemoteOperations(true)
.AllowColumnReordering(false)
.AllowColumnResizing(false)
.ColumnAutoWidth(true)
.ColumnFixing(c => c.Enabled(true))
.Columns(columns => {


columns.AddFor(m => m.ID).Width(50).Fixed(true);

@*columns.AddFor(m => m.FlightID).Width(100);*@


 //columns.AddFor(m => m.TimeKey).Width(0);

columns.AddFor(m => m.Date).Width(100).Fixed(true);
columns.AddFor(m => m.Date_Color).Width(0).Fixed(true);

columns.AddFor(m => m.FltNo).Width(80).Fixed(true)
.CellTemplate(@<text>
             <a href="@Url.Action("FlightOne", "FlightDate")?FlightId=<%- data.FlightID %>"><span style="color:#0204fd;font-weight:bold;"><%-value%></span></a>
        </text>);
columns.AddFor(m => m.FltNo_Color).Width(0);

columns.AddFor(m => m.RegisterNo);
columns.AddFor(m => m.RegisterNo_Color).Width(0);

columns.AddFor(m => m.Aircraft);
columns.AddFor(m => m.Aircraft_Color).Width(0);

columns.AddFor(m => m.Route);
columns.AddFor(m => m.Route_Color).Width(0);

columns.AddFor(m => m.DateTime_ATA);
columns.AddFor(m => m.DateTime_ATA_Color).Width(0);

columns.Add()
.Caption("STD/ETD")
.Width(100)
.CalculateCellValue(@<text>
                function(data) {
                    return [
                        data.STD, data.ETD]
                        .join("/");
                }
            </text>);

columns.AddFor(m => m.BDT);
columns.AddFor(m => m.BDT_Color).Width(0);

columns.AddFor(m => m.DoorClose);
columns.AddFor(m => m.DoorClose_Color).Width(0);

columns.AddFor(m => m.TOff);
columns.AddFor(m => m.TOff_Color).Width(0);

columns.Add()
.Caption("STA/ETA")
.Width(100)
.CalculateCellValue(@<text>
                function(data) {
                    return [
                        data.STA, data.ETA]
                        .join("/");
                }
            </text>);

    columns.AddFor(m => m.TDown);
    columns.AddFor(m => m.TDown_Color).Width(0);

    columns.AddFor(m => m.ATD);
    columns.AddFor(m => m.ATD_Color).Width(0);


    columns.AddFor(m => m.ATA);
    columns.AddFor(m => m.ATA_Color).Width(0);


    columns.AddFor(m => m.Terminal);
    columns.AddFor(m => m.Terminal_Color).Width(0);


    columns.AddFor(m => m.Gate);
    columns.AddFor(m => m.Gate_Color).Width(0);


    columns.AddFor(m => m.Belt_Dep);

    columns.AddFor(m => m.Belt_Dep_Color).Width(0);


    columns.AddFor(m => m.Bay_Dep);
    columns.AddFor(m => m.Bay_Dep_Color).Width(0);

    columns.AddFor(m => m.Bay_Arr);
    columns.AddFor(m => m.Bay_Arr_Color).Width(0);


})
    .Paging(p => p.PageSize(10))
    .ShowBorders(true)
    .ShowColumnLines(true)
    //.OnCellPrepared("cell_prepared")
    .ShowRowLines(true)
    .WordWrapEnabled(true)
    .FilterRow(f => f.Visible(true))
    .HeaderFilter(f => f.Visible(false))
    .GroupPanel(p => p.Visible(true))
    .Grouping(g => g.AutoExpandAll(false))
    .RemoteOperations(true)
    .GroupPanel(z => z.AllowColumnDragging(false))
    .Pager(pager =>
    {
        pager.ShowPageSizeSelector(true);
        pager.AllowedPageSizes(new[] { 10, 20, 50 });
        pager.ShowInfo(true);
    })
    .Summary(s => s.TotalItems(totalItems =>
    {   totalItems.AddFor(m => m.FlightID).SummaryType(SummaryType.Count).ShowInColumn("FltNo").DisplayFormat("Flt: {0}");

    })

  )
)

BOC/Views/FlightDate/FlightDoc.cshtml
@{
    ViewData["Title"] = "FlightDoc";
    Layout = "~/Views/Shared/_DeskTop.cshtml";
}


@using BOC.Models;
@model List<FlightDoc>;

<style>
    #box {
        background-color: #006BB8;
        width: 100%;
        border-radius: 25px;
        padding: 5px;
        margin: 5px;
    }

    #div1 {
        height: 30px;
        width: 20%;
        float: left;
        color: #333;
        font-family: Tahoma;
    }

    #div2 {
        height: 30px;
        width: 30%;
        border: solid 1px #acd9f5;
        float: left;
        margin-bottom: 5px;
        color: #333;
        font-family: Tahoma;
    }
   

    #div1, #div2 {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }

    .inline {
        display: inline-block;
        margin: 2px;
    }
  
</style>
<script>
    $(function () {
        document.getElementById("doc").innerHTML = "No electricity!";
    });
</script>
<div class="container" style="padding-top:60px;">
    @if (Model == null)
    {
        <p id="doc"></p>
    }
    else
    {
         foreach (var item in Model)
    {
        if (@item.OddEvent == 0)
        {
    <div style="background-color:#f4fab5">
        <div class="row">
            <div class="col">
                <b>Airport:</b>@item.Airport.ToString()
            </div>
            <div class="col">
                <b>Doctype/RouteType:</b>@item.DocumentType.ToString()/@item.RouteType.ToString()
            </div>
        </div>
        <div class="row">
            <div class="col">
                <b>User:</b>@item.UserUpdate.ToString()
            </div>
            <div class="col">
                <b>Last Update:</b>@item.RecDate.ToString()
            </div>
        </div>
        <div class="row">
            <div style="height:auto;width:100%!important;margin:15px;">
                <b>Content:</b><br />
                <span style="white-space: pre-line">@item.Content.ToString()</span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <b>FileName:</b>@item.FileName.ToString()
            </div>

        </div>
    </div>
        }
        else
        {
            <div style="background-color:#c4defb;">
                <div class="row">
                    <div class="col">
                        <b>Airport:</b>@item.Airport.ToString()
                    </div>
                    <div class="col">
                        <b>Doctype/RouteType:</b>@item.DocumentType.ToString()/@item.RouteType.ToString()
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <b>User:</b>@item.UserUpdate.ToString()
                    </div>
                    <div class="col">
                        <b>Last Update:</b>@item.RecDate.ToString()
                    </div>
                </div>
                <div class="row">
                    <div style="height:auto;width:100%!important;margin:15px;">
                    <b>Content:</b><br />
                    <span style="white-space: pre-line">@item.Content.ToString()</span></div>
                </div>
                <div class="row">
                    <div class="col">
                        <b>FileName:</b>@item.FileName.ToString()
                    </div>

                </div>
            </div>

        }


    }
    }

</div>

BOC/Views/FlightDate/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DeskTop.cshtml";
}



@using BOC.Models;
@model LoungeModel;


<style>
    fieldset {
        border: 1px solid #ddd !important;
        margin: 0;
        min-width: 0;
        padding: 10px;
        position: relative;
        border-radius: 4px;
        background-color: #f5f5f5;
        padding-left: 10px !important;
    }

    legend {
        font-size: 14px;
        font-weight: bold;
        margin-bottom: 0px;
        width: 35%;
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px 5px 5px 10px;
        background-color: #ffffff;
    }

    .dx-fieldset {
        height: 500px;
    }

    .dx-texteditor-container {
        width: 400px;
    }
</style>

<div class="container" style="padding-top:60px;">

    <div class="panel panel-default">

        <div class="panel-body" style="padding-left:10px;">

            <form method="post"  id="frmFlightDate" enctype="multipart/form-data" asp-controller="FlightDate" asp-action="Detail">
                <fieldset class="col-md-6">
                    <legend>Flight Filter</legend>

                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="row">
                                &ensp;&ensp; Station:&ensp;&ensp;&ensp;&ensp;&ensp;
                                @(Html.DevExtreme().DropDownBoxFor(model => model.AirportChoose)
    .ID("dropDownBox")
    .ValueExpr("ID")
    .DisplayExpr(new JS("gridBox_displayExpr"))
    .DataSource(d => d.Mvc()
        .Controller("FlightDate/Detail")
        .LoadAction("Post")
        .LoadMode(DataSourceLoadMode.Raw)
        .Key(Model.AirportChoose)
    )
    .Width("380")
    .Placeholder("Select Your Station....")
    .ShowClearButton(true)
    .OnValueChanged("gridBox_valueChanged")
    .ContentTemplate(new TemplateName("EmbeddedDataGridSingle"))
                            )
                                @using (Html.DevExtreme().NamedTemplate("EmbeddedDataGridSingle"))
                                {
                                    @(Html.DevExtreme().DataGrid()
                .ID("embedded-datagrid")
                .DataSource(Model.ListAirport, "Airport")
                .Columns(columns => {
                    columns.Add().DataField("Airport").Width(0);
                    columns.Add().DataField("AirportName");
                    columns.Add().DataField("CityName");
                    columns.Add().DataField("CountryName");
                })
                .HoverStateEnabled(true)
                .Paging(p => p.PageSize(10))
                .FilterRow(f => f.Visible(true))
                .Scrolling(s => s.Mode(GridScrollingMode.Infinite))
                .Height(345)
                .Width(380)
                .Selection(s => s.Mode(SelectionMode.Single))
                //.SelectedRowKeys(new JS(@"[component.option(""key"")]"))
                .SelectedRowKeys(Model.AirportChoose)
                .OnSelectionChanged(@<text>
                        function(selectedItems) {
                            var keys = selectedItems.selectedRowKeys;
                            component.option("value", keys);

                          }
                    </text>)
                )
                                }


                            </div><br />
                                  <div class="row">
                                      &ensp;&ensp; Date:&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;@Html.TextBoxFor(model => model.Date,
new { placeholder = "dd/mm/yyyy", id = "datepicker", style = "width:380px;" })
                                      @*<input data-date-format="dd/mm/yyyy" id="datepicker">*@

                                  </div>
                            <br />
                            <div class="row">
                                &ensp;&ensp; Route Type:&ensp;
                                @Html.DropDownListFor(model => model.SelectedRouting, new SelectList((IEnumerable<SelectListItem>)ViewBag.List, "Value", "Text"), new { @class = "dropdown" , style = "width:380px;" })
          
                            </div><br />
                            <div class="row">&ensp;&ensp; Key Search:&ensp;@Html.TextBoxFor(model => model.Key,new { style = "width:380px;" })@*<input type="text" id="key" />*@</div><br />
                            <div class="row">
                                &ensp;&ensp; Time Zone:&ensp;&ensp;
                                <input type="checkbox" name="check" value="HAN" checked onclick="onlyOne(this)"> &ensp;&ensp;HAN&ensp;&ensp;
                                <input type="checkbox" name="check" value="UTC" onclick="onlyOne(this)">&ensp;&ensp;UTC&ensp;&ensp;
                                <input type="checkbox" name="check" value="LOCAL" onclick="onlyOne(this)">&ensp;&ensp;LOCAL&ensp;&ensp;

                                @Html.HiddenFor(model => model.TimeZone, new { @id = "TimeZone" })
                            </div><br />
                                  <div class="row">&ensp;&ensp;View Type:&ensp;&ensp;@Html.TextBoxFor(model => model.ViewType, new { style = "width:380px;" })@*<input type="text" id="viewtype" />*@</div><br />
                            <div class="row">&ensp;&ensp;@Html.CheckBoxFor(model => model.AutoHide)@*<input type="checkbox" name="checkbox">*@ &ensp;&ensp;Auto Hide&ensp;&ensp;</div>
                            <input type="submit" id="filter" value="OK" class="btn btn-primary" style="float:right" />

                        </div>
                    </div>

                </fieldset>

            </form>
        </div>

    </div>
</div>
<input type="hidden" id="error" value="@Model.ErrorMessage" />

       <!-- bootstrap -->
<script src="~/js/bootstrap-datepicker.min.js"></script>

<script type="text/javascript">
    /*Format datepicker bootstrap*/

    $('#datepicker').datepicker({
        weekStart: 1,
        daysOfWeekHighlighted: "6,0",
        autoclose: true,
        todayHighlight: true,
        format: 'dd/mm/yyyy'
       

    });

   
     
    $('#datepicker').datepicker("setDate", new Date());

    function onlyOne(checkbox) {
        var checkboxes = document.getElementsByName('check')
        checkboxes.forEach((item) => {
            if (item !== checkbox) item.checked = false
        })
        //Bind value timezone checked
        $.each($("input[name='check']:checked"), function () {
            $('#TimeZone').val($(this).val());

        });

    }




    function gridBox_valueChanged(e) {
        let element = document.getElementById("embedded-datagrid");
        let instance = DevExpress.ui.dxAccordion.getInstance(element);
        if (element.length) {
            var dataGrid = element.dxDataGrid(instance);
            dataGrid.selectRows(e.value, false);

        }
    }

    function gridBox_displayExpr(item) {
        return item && item.Airport;

    }

    $(function () {
        if ($("#error").val() !== "") {
            alertify.alert($("#error").val());

        }
    
    })





</script>